void sendScreen(void);
Matrix4 ortho(float width, float height, float zfar, float znear);
uint8_t project(Vector2 * projVector, Vector3 v, Matrix4 proj, uint32_t width, uint32_t height);
Matrix4 rotate(float degrees, int axis);
Matrix4 translate(Vector3 translation);
Matrix4 scale(Vector3 scalar);
void drawPoint(Vector2 point, int16_t color);
void drawLine(Vector2 point1, Vector2 point2, int16_t color);
Matrix4 lookAt(Vector3 cameraPosition, Vector3 target, Vector3 up);
Matrix4 FPSView(Vector3 cameraPosition, float pitch, float yaw );
Matrix4 pers(float fovx, float fovy, float zfar, float znear);
float clamp(float value);
float interpolate(float min, float max, float gradient);
void drawScanline(int y, Vector2 pa, Vector2 pb, Vector2 pc, Vector2 pd, int16_t color);
void drawTriangle(Vector2 p1, Vector2 p2, Vector2 p3, int16_t color);
